insert into PV_LogTypes (name, ref1description, ref2description, val1description, val2description)
values ('Run Workflow Media', 'mediafileid', 'commentid', 'Hora de inicio','workflowParams')
insert into PV_LogTypes (name, ref1description, ref2description, val1description, val2description)
values ('End Workflow Media', 'mediafileid', 'commentid', 'Hora de finalizacion','Resultado del workflow')
insert into PV_LogTypes (name, ref1description, ref2description, val1description, val2description)
values ('Run Workflow Validez', 'mediafileid', 'commentid', 'Hora de inicio','workflowParams')
insert into PV_LogTypes (name, ref1description, ref2description, val1description, val2description)
values ('End Workflow Validez', 'mediafileid', 'commentid', 'Hora de finalizacion','Resultado del mediafile')
insert into PV_LogTypes (name, ref1description, ref2description, val1description, val2description)
values ('Failed Comment Reason', 'proposalid', 'commentid', 'Hora de Rechazo','Razon del rechazo')
insert into PV_LogSource (name) values ('Workflow');